baseURL = "https://kieranwilkinson.co.uk/"
theme = "hugo-bearcub"
copyright = "Kieran Wilkinson"
defaultContentLanguage = "en"
enableRobotsTXT = true

[taxonomies]
  tag = "tags"

[[menu.main]]
name     = "Contributions"
url      = "/contributions/"
weight   = 1

[[menu.main]]
name     = "Journal"
url      = "/journal/"
weight   = 2

[markup]
  [markup.goldmark.parser.attribute]
    block = true
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[languages]
  [languages.en]
    title = "Kieran Wilkinson"
    languageName = "English"
    LanguageCode = "en-GB"
    contentDir = "content"

[params]
  mainSections = ["journal"]
  description = "Confident creative technologist and real-time technical director with experience in large-scale projects spanning film visual effects, games, and on-set virtual production."
  favicon = "images/favicon.ico"
  title = "Kieran Wilkinson"
  dateFormat = "2 Jan 2006"

  [params.author]
    name = "Kieran Wilkinson"
    email = "kieranlukewilkinson@gmail.com"
