baseURL = "https://kieranwilkinson.co.uk/"
theme = "hugo-bearcub"
copyright = "Kieran Wilkinson"
defaultContentLanguage = "en"
enableRobotsTXT = true

[[menu.main]]
name     = "Archive"
url      = "/archive/"
weight   = 1

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[languages]
  [languages.en]
    title = "Hello, I’m Kieran Wilkinson. 👋"
    languageName = "en-US 🇺🇸"
    LanguageCode = "en-US"
    contentDir = "content"
    [languages.en.params]
      madeWith = "© 2026"

[params]
  description = """
Confident creative technologist and real-time technical director \
with experience in large-scale projects spanning film visual effects, \ 
games, and on-set virtual production.\
"""
  favicon = "images/favicon.ico"
  images = ["images/share.webp"]
  title = "Kieran Wilkinson"
  dateFormat = "2006-01-02"
  hideUntranslated = true
  themeStyle = "original"
  generateSocialCard = true

  # Social media. Delete any item you aren't using to make sure it won't show up
  # in your website's metadata.
  [params.social]
    github = "https://github.com/kieranwilkinson"

  [params.author]
    name = "Kieran Wilkinson" # Your name as shown in the RSS feed metadata
    email = "kieranlukewilkinson@gmail.com" # Added to the footer so readers can reply to posts